/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import util.View;

/**
 *
 * @author SiziJayawardena
 */
public class Admission extends javax.swing.JFrame implements View{

    /**
     * Creates new form Admission
     */
    public Admission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAdmissionID = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNICP = new javax.swing.JTextField();
        txtLNameP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddressP = new javax.swing.JTextArea();
        txtFNameP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        radioMaleP = new javax.swing.JRadioButton();
        radioFemaleP = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        checkP = new javax.swing.JCheckBox();
        btnSearchOldID = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtAgeP = new javax.swing.JTextField();
        txtTelP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        comboConsID = new javax.swing.JComboBox<>();
        comboWardNo = new javax.swing.JComboBox<>();
        comboDocID = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtFNameG = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtLNameG = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNICG = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressG = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        txtTelG = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        radioMaleG = new javax.swing.JRadioButton();
        radioFemaleG = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        checkG = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        comboOldIDG = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        txtGuardianID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Admission", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Admission ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 30));

        txtAdmissionID.setEditable(false);
        txtAdmissionID.setBackground(new java.awt.Color(204, 204, 204));
        txtAdmissionID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(txtAdmissionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 90, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("First Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jLabel10.setText("Address");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        jLabel16.setText("Consultant ID");
        jLabel16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel16FocusGained(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        txtNICP.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(txtNICP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 140, 30));
        jPanel2.add(txtLNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 30));

        jLabel9.setText("Last Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        txtAddressP.setColumns(20);
        txtAddressP.setRows(5);
        jScrollPane2.setViewportView(txtAddressP);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 180, 50));
        jPanel2.add(txtFNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 140, 30));

        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("NIC");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 30));

        jLabel15.setText("Ward No.");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 30));

        buttonGroup2.add(radioMaleP);
        radioMaleP.setText("Male");
        jPanel2.add(radioMaleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 30));

        buttonGroup2.add(radioFemaleP);
        radioFemaleP.setText("Female");
        jPanel2.add(radioFemaleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, 30));

        jLabel12.setText("Gender");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, 30));

        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setText("Has old Patient ID?");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 40));

        checkP.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(checkP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -10, -1, 60));

        btnSearchOldID.setBackground(new java.awt.Color(204, 255, 255));
        btnSearchOldID.setForeground(new java.awt.Color(255, 51, 51));
        btnSearchOldID.setText("Search");
        jPanel2.add(btnSearchOldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 90, -1));

        jLabel11.setText("Age");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));
        jPanel2.add(txtAgeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 30));
        jPanel2.add(txtTelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, 30));

        jLabel13.setText("Tel No.");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel24.setText("Doctor ID");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 30));

        jLabel27.setText("Date ");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 30));

        txtDate.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 102, 102));
        txtDate.setText("YYYY-MM-DD");
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
        });
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 100, 30));

        comboConsID.setForeground(new java.awt.Color(51, 51, 255));
        comboConsID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comboConsID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboConsIDFocusGained(evt);
            }
        });
        jPanel2.add(comboConsID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 90, -1));

        comboWardNo.setForeground(new java.awt.Color(51, 51, 255));
        comboWardNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comboWardNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboWardNoFocusGained(evt);
            }
        });
        jPanel2.add(comboWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 90, -1));

        comboDocID.setForeground(new java.awt.Color(51, 51, 255));
        comboDocID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comboDocID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboDocIDFocusGained(evt);
            }
        });
        jPanel2.add(comboDocID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 90, 30));

        jTabbedPane1.addTab("Patient Details", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("First Name");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));
        jPanel3.add(txtFNameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, 30));

        jLabel19.setText("Last Name");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));
        jPanel3.add(txtLNameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, 30));

        jLabel20.setText("NIC");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));
        jPanel3.add(txtNICG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 30));

        jLabel21.setText("Address");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtAddressG.setColumns(20);
        txtAddressG.setRows(5);
        jScrollPane3.setViewportView(txtAddressG);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 260, 60));

        jLabel22.setText("Tel No.");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, -1, 20));
        jPanel3.add(txtTelG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, 30));

        jLabel23.setText("Gender");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 30));

        buttonGroup1.add(radioMaleG);
        radioMaleG.setText("Male");
        jPanel3.add(radioMaleG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 30));

        buttonGroup1.add(radioFemaleG);
        radioFemaleG.setText("Female");
        jPanel3.add(radioFemaleG, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 30));

        jLabel26.setForeground(new java.awt.Color(255, 51, 51));
        jLabel26.setText("Has old Guardian ID?");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 30));

        checkG.setForeground(new java.awt.Color(51, 51, 255));
        jPanel3.add(checkG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 50));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Old ID");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 30));

        comboOldIDG.setForeground(new java.awt.Color(255, 51, 51));
        comboOldIDG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comboOldIDG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboOldIDGFocusGained(evt);
            }
        });
        jPanel3.add(comboOldIDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 90, 30));

        jLabel6.setFont(new java.awt.Font("Lithos Pro", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Press 'Tab'");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jTabbedPane1.addTab("Guardian Details", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 520, 300));

        jLabel2.setText("Patient ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        txtPatientID.setEditable(false);
        txtPatientID.setBackground(new java.awt.Color(204, 204, 204));
        txtPatientID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 30));

        btnBack.setText("Back");
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(204, 204, 255));
        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(51, 51, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 100, 30));

        btnGenerate.setForeground(new java.awt.Color(255, 51, 51));
        btnGenerate.setText("Generate");
        jPanel1.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, -1));

        txtGuardianID.setEditable(false);
        txtGuardianID.setBackground(new java.awt.Color(204, 204, 204));
        txtGuardianID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(txtGuardianID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, 30));

        jLabel3.setText("Guardian ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 30));

        btnClear.setText("Clear");
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        txtDate.setText(null);
    }//GEN-LAST:event_txtDateFocusGained

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void jLabel16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel16FocusGained
        
    }//GEN-LAST:event_jLabel16FocusGained

    private void comboConsIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboConsIDFocusGained
        
    }//GEN-LAST:event_comboConsIDFocusGained

    private void comboWardNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboWardNoFocusGained
        
    }//GEN-LAST:event_comboWardNoFocusGained

    private void comboDocIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboDocIDFocusGained
        
    }//GEN-LAST:event_comboDocIDFocusGained

    private void comboOldIDGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboOldIDGFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOldIDGFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSearchOldID;
    private javax.swing.JButton btnSubmit;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JCheckBox checkG;
    public javax.swing.JCheckBox checkP;
    public javax.swing.JComboBox<String> comboConsID;
    public javax.swing.JComboBox<String> comboDocID;
    public javax.swing.JComboBox<String> comboOldIDG;
    public javax.swing.JComboBox<String> comboWardNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JRadioButton radioFemaleG;
    public javax.swing.JRadioButton radioFemaleP;
    public javax.swing.JRadioButton radioMaleG;
    public javax.swing.JRadioButton radioMaleP;
    public javax.swing.JTextArea txtAddressG;
    public javax.swing.JTextArea txtAddressP;
    public javax.swing.JTextField txtAdmissionID;
    public javax.swing.JTextField txtAgeP;
    public javax.swing.JTextField txtDate;
    public javax.swing.JTextField txtFNameG;
    public javax.swing.JTextField txtFNameP;
    public javax.swing.JTextField txtGuardianID;
    public javax.swing.JTextField txtLNameG;
    public javax.swing.JTextField txtLNameP;
    public javax.swing.JTextField txtNICG;
    public javax.swing.JTextField txtNICP;
    public javax.swing.JTextField txtPatientID;
    public javax.swing.JTextField txtTelG;
    public javax.swing.JTextField txtTelP;
    // End of variables declaration//GEN-END:variables
    
    public JButton getBtnBack(){
        return btnBack;
    }
    
    public JButton getBtnSubmit(){
        return btnSubmit;
    }

    public JButton getBtnGenerate(){
        return btnGenerate;
    }
    
    public JComboBox getComboConsID(){
        return comboConsID;
    }
    
    public JComboBox getComboWardNo(){
        return comboWardNo;
    }
    
    public JComboBox getComboDocID(){
        return comboDocID;
    }
    
    public JComboBox getComboOldIDG(){
        return comboOldIDG;
    }
    
    public JButton getBtnSearchOldID(){
        return btnSearchOldID;
    }
    
    public JButton getBtnClear(){
        return btnClear;
    }
}
