/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

import javax.swing.JButton;
import util.View;

/**
 *
 * @author SiziJayawardena
 */
public class PatientDetails extends javax.swing.JFrame implements View {

    /**
     * Creates new form PatientDetails
     */
    public PatientDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtFNameP = new javax.swing.JTextField();
        txtLNameP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddressP = new javax.swing.JTextArea();
        txtConsID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        radioMaleP = new javax.swing.JRadioButton();
        radioFemaleP = new javax.swing.JRadioButton();
        txtWardNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNICP = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAgeP = new javax.swing.JTextField();
        btnUpdateP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtFNameG = new javax.swing.JTextField();
        txtLNameG = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressG = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        radioMaleG = new javax.swing.JRadioButton();
        radioFemaleG = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        txtNICG = new javax.swing.JTextField();
        txtTelG = new javax.swing.JTextField();
        btnUpdateG = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtGuardianID = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDesTest = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtComTest = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtDateTest = new javax.swing.JTextField();
        comboTest = new javax.swing.JComboBox<>();
        btnSearchTest = new javax.swing.JButton();
        btnUpdateTest = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComTreat = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesTreat = new javax.swing.JTextArea();
        btnSearchTreat = new javax.swing.JButton();
        comboTreat = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtDateTreat = new javax.swing.JTextField();
        btnUpdateTreat = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        txtPatientID.setBackground(new java.awt.Color(204, 204, 204));
        txtPatientID.setForeground(new java.awt.Color(51, 51, 255));
        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 30));

        btnSearch.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 255));
        btnSearch.setText("Search");
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("First Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel2.add(txtFNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 30));
        jPanel2.add(txtLNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, 30));

        jLabel9.setText("Last Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel10.setText("Address");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtAddressP.setColumns(20);
        txtAddressP.setRows(5);
        jScrollPane2.setViewportView(txtAddressP);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, 60));
        jPanel2.add(txtConsID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 80, 30));

        jLabel11.setText("NIC");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        jLabel12.setText("Gender");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, 30));

        buttonGroup1.add(radioMaleP);
        radioMaleP.setText("Male");
        jPanel2.add(radioMaleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 30));

        buttonGroup1.add(radioFemaleP);
        radioFemaleP.setText("Female");
        jPanel2.add(radioFemaleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, 30));
        jPanel2.add(txtWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 140, 30));

        jLabel13.setText("Age");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel14.setText("Tel No.");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));
        jPanel2.add(txtNICP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));

        jLabel15.setText("Ward No.");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));
        jPanel2.add(txtTelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 140, 30));

        jLabel16.setText("Consultant Doc ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel2.add(txtAgeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 140, 30));

        btnUpdateP.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdateP.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdateP.setText("Update");
        jPanel2.add(btnUpdateP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jTabbedPane1.addTab("Patient Details", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("First Name");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel4.add(txtFNameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 30));
        jPanel4.add(txtLNameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, 30));

        jLabel18.setText("Last Name");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel19.setText("Address");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtAddressG.setColumns(20);
        txtAddressG.setRows(5);
        jScrollPane3.setViewportView(txtAddressG);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, 60));

        jLabel20.setText("NIC");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        jLabel21.setText("Gender");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        buttonGroup2.add(radioMaleG);
        radioMaleG.setText("Male");
        jPanel4.add(radioMaleG, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 30));

        buttonGroup2.add(radioFemaleG);
        radioFemaleG.setText("Female");
        jPanel4.add(radioFemaleG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 30));

        jLabel23.setText("Tel No.");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));
        jPanel4.add(txtNICG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 30));
        jPanel4.add(txtTelG, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 140, 30));

        btnUpdateG.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdateG.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdateG.setText("Update");
        jPanel4.add(btnUpdateG, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel26.setText("Guardian ID");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        txtGuardianID.setBackground(new java.awt.Color(204, 255, 255));
        txtGuardianID.setForeground(new java.awt.Color(0, 0, 255));
        jPanel4.add(txtGuardianID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 110, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 260));

        jTabbedPane1.addTab("Guardian Details", jPanel3);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Test ID");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 24, -1, 20));

        jLabel7.setText("Description");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtDesTest.setColumns(20);
        txtDesTest.setRows(5);
        jScrollPane5.setViewportView(txtDesTest);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel22.setText("Comments");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtComTest.setColumns(20);
        txtComTest.setRows(5);
        jScrollPane6.setViewportView(txtComTest);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel24.setText("Date");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 30));

        txtDateTest.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtDateTest.setForeground(new java.awt.Color(0, 102, 102));
        txtDateTest.setText("YYYY-MM-DD");
        jPanel6.add(txtDateTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 100, 30));

        comboTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", " " }));
        comboTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTestActionPerformed(evt);
            }
        });
        jPanel6.add(comboTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        btnSearchTest.setForeground(new java.awt.Color(0, 0, 255));
        btnSearchTest.setText("Search");
        jPanel6.add(btnSearchTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        btnUpdateTest.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdateTest.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdateTest.setText("Update");
        jPanel6.add(btnUpdateTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jTabbedPane1.addTab("Test(s)", jPanel6);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Treatment ID");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 24, -1, 20));

        jLabel4.setText("Comments");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setText("Description");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtComTreat.setColumns(20);
        txtComTreat.setRows(5);
        jScrollPane1.setViewportView(txtComTreat);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        txtDesTreat.setColumns(20);
        txtDesTreat.setRows(5);
        jScrollPane4.setViewportView(txtDesTreat);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        btnSearchTreat.setForeground(new java.awt.Color(0, 0, 255));
        btnSearchTreat.setText("Search");
        jPanel5.add(btnSearchTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        comboTreat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "     ", " " }));
        comboTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTreatActionPerformed(evt);
            }
        });
        jPanel5.add(comboTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        jLabel25.setText("Date");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 30));

        txtDateTreat.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtDateTreat.setForeground(new java.awt.Color(0, 102, 102));
        txtDateTreat.setText("YYYY-MM-DD");
        jPanel5.add(txtDateTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 100, 30));

        btnUpdateTreat.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdateTreat.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdateTreat.setText("Update");
        jPanel5.add(btnUpdateTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jTabbedPane1.addTab("Treatment(s)", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 610, 300));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void comboTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTreatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTreatActionPerformed

    private void comboTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    public javax.swing.JButton btnSearchTest;
    public javax.swing.JButton btnSearchTreat;
    private javax.swing.JButton btnUpdateG;
    private javax.swing.JButton btnUpdateP;
    private javax.swing.JButton btnUpdateTest;
    private javax.swing.JButton btnUpdateTreat;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JComboBox<String> comboTest;
    public javax.swing.JComboBox<String> comboTreat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JRadioButton radioFemaleG;
    public javax.swing.JRadioButton radioFemaleP;
    public javax.swing.JRadioButton radioMaleG;
    public javax.swing.JRadioButton radioMaleP;
    public javax.swing.JTextArea txtAddressG;
    public javax.swing.JTextArea txtAddressP;
    public javax.swing.JTextField txtAgeP;
    public javax.swing.JTextArea txtComTest;
    public javax.swing.JTextArea txtComTreat;
    public javax.swing.JTextField txtConsID;
    public javax.swing.JTextField txtDateTest;
    public javax.swing.JTextField txtDateTreat;
    public javax.swing.JTextArea txtDesTest;
    public javax.swing.JTextArea txtDesTreat;
    public javax.swing.JTextField txtFNameG;
    public javax.swing.JTextField txtFNameP;
    public javax.swing.JTextField txtGuardianID;
    public javax.swing.JTextField txtLNameG;
    public javax.swing.JTextField txtLNameP;
    public javax.swing.JTextField txtNICG;
    public javax.swing.JTextField txtNICP;
    public javax.swing.JTextField txtPatientID;
    public javax.swing.JTextField txtTelG;
    public javax.swing.JTextField txtTelP;
    public javax.swing.JTextField txtWardNo;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBack(){
        return btnBack;
    }
    
    public JButton getBtnSearch(){
        return btnSearch;
    }
    
    public JButton getBtnSearchTest(){
        return btnSearchTest;
    }
    
    public JButton getBtnSearchTreat(){
        return btnSearchTreat;
    }
    
    public JButton getBtnUpdateP(){
        return btnUpdateP;
    }
    
    public JButton getBtnUpdateG(){
        return btnUpdateG;
    }
    
    public JButton getBtnUpdateTest(){
        return btnUpdateTest;
    }
    
    public JButton getBtnUpdateTreat(){
        return btnUpdateTreat;
    }
}
