/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

import javax.swing.JButton;
import util.UIFactory;
import util.View;

/**
 *
 * @author SiziJayawardena
 */
public class Patient extends javax.swing.JFrame implements View {

    /**
     * Creates new form PatientDetails
     */
    public Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDetails = new javax.swing.JButton();
        btnNewAd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNewTT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDetails.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnDetails.setForeground(new java.awt.Color(51, 51, 255));
        btnDetails.setText("Patient Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, 40));

        btnNewAd.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnNewAd.setForeground(new java.awt.Color(51, 51, 255));
        btnNewAd.setText("New Admission");
        btnNewAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAdActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, 40));

        btnBack.setText("Back");
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnNewTT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnNewTT.setForeground(new java.awt.Color(51, 51, 255));
        btnNewTT.setText("New Test/Treat");
        btnNewTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTTActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewAdActionPerformed

    private void btnNewTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewTTActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnNewAd;
    private javax.swing.JButton btnNewTT;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public JButton getBtnNew(){
    return btnNewAd;
}

public JButton getBtnDetails(){
    return btnDetails;
}

public JButton getBtnBack(){
    return btnBack;
}

public JButton getBtnNewTT(){
    return btnNewTT;
}

public JButton getBtnNewAd(){
    return btnNewAd;
}
}
