/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

import javax.swing.JButton;
import util.View;

/**
 *
 * @author SiziJayawardena
 */
public class Payment extends javax.swing.JFrame implements View{

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdmissionID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblIDExist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Make Payment", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Payment ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 30));

        txtPaymentID.setEditable(false);
        txtPaymentID.setBackground(new java.awt.Color(204, 204, 255));
        txtPaymentID.setForeground(new java.awt.Color(51, 51, 255));
        txtPaymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 70, 30));

        jLabel2.setText("Admission ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        txtAdmissionID.setBackground(new java.awt.Color(204, 255, 255));
        txtAdmissionID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(txtAdmissionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, 30));

        jLabel3.setText("Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        txtAmount.setForeground(new java.awt.Color(0, 0, 153));
        txtAmount.setText("LKR");
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 30));

        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        txtDate.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtDate.setForeground(new java.awt.Color(153, 153, 255));
        txtDate.setText("YYYY-MM-DD");
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 30));

        btnPay.setForeground(new java.awt.Color(51, 51, 255));
        btnPay.setText(" PAY");
        jPanel1.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        btnBack.setText("Back");
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblName.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 280, 30));

        lblName1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jPanel1.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 30));

        lblIDExist.setFont(new java.awt.Font("Mshtakan", 2, 15)); // NOI18N
        jPanel1.add(lblIDExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblIDExist;
    public javax.swing.JLabel lblName;
    public javax.swing.JLabel lblName1;
    public javax.swing.JTextField txtAdmissionID;
    public javax.swing.JTextField txtAmount;
    public javax.swing.JTextField txtDate;
    public javax.swing.JTextField txtPaymentID;
    // End of variables declaration//GEN-END:variables
    
    public JButton getBtnBack(){
        return btnBack;
    }
    
    public JButton getBtnPay(){
        return btnPay;
    }

}
