/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeDetails;

import javax.swing.JButton;
import util.UIFactory;
import util.View;

/**
 *
 * @author SiziJayawardena
 */
public class AddNewEmployee extends javax.swing.JFrame implements View {

    /**
     * Creates new form AddNewEmployee
     */
    public AddNewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDocID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSLMC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioFemale = new javax.swing.JRadioButton();
        radioMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        btnNewDoc = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNurseID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFNameN = new javax.swing.JTextField();
        txtLNameN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddressN = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        radioMaleN = new javax.swing.JRadioButton();
        radioFemaleN = new javax.swing.JRadioButton();
        txtNICN = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnNewNurse = new javax.swing.JButton();
        txtTelN = new javax.swing.JTextField();
        txtMailN = new javax.swing.JTextField();
        txtWardNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtEmpIDN = new javax.swing.JTextField();
        btnGenerateN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtFNameS = new javax.swing.JTextField();
        txtLNameS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressS = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        radioMaleS = new javax.swing.JRadioButton();
        radioFemaleS = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        txtNICS = new javax.swing.JTextField();
        txtTelS = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtEmpIDS = new javax.swing.JTextField();
        btnNewStaff = new javax.swing.JButton();
        btnGenerateS = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtMailS = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Employee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setForeground(new java.awt.Color(51, 51, 255));
        jTabbedPane3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Doctor ID");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        txtDocID.setEditable(false);
        txtDocID.setBackground(new java.awt.Color(204, 204, 204));
        txtDocID.setForeground(new java.awt.Color(0, 0, 255));
        jPanel4.add(txtDocID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 40));

        jLabel2.setText("First Name");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));
        jPanel4.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel3.setText("Employee ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 40));
        jPanel4.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));

        jLabel4.setText("SLMC Registered No.");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, -1, 30));
        jPanel4.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 30));

        jLabel5.setText("Address");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));
        jPanel4.add(txtSLMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 130, 30));

        jLabel6.setText("Last Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 70));

        jLabel7.setText("Tel. No.");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        txtEmpID.setEditable(false);
        txtEmpID.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpID.setForeground(new java.awt.Color(0, 0, 255));
        jPanel4.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, 40));

        jLabel8.setText("Gender");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        buttonGroup1.add(radioFemale);
        radioFemale.setText("Female");
        jPanel4.add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        buttonGroup1.add(radioMale);
        radioMale.setText("Male");
        jPanel4.add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel9.setText("e-mail");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));
        jPanel4.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));

        jLabel10.setText("NIC No.");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, 20));
        jPanel4.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));

        btnNewDoc.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnNewDoc.setForeground(new java.awt.Color(0, 0, 255));
        btnNewDoc.setText("Add New Doctor");
        jPanel4.add(btnNewDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 269, -1, 40));

        btnGenerate.setForeground(new java.awt.Color(255, 51, 51));
        btnGenerate.setText("Generate");
        jPanel4.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jTabbedPane3.addTab("Doctor", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Nurse ID");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        txtNurseID.setEditable(false);
        txtNurseID.setBackground(new java.awt.Color(204, 204, 204));
        txtNurseID.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(txtNurseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 40));

        jLabel12.setText("First Name");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));

        jLabel13.setText("Last Name");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));
        jPanel5.add(txtFNameN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));
        jPanel5.add(txtLNameN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel14.setText("Address");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        txtAddressN.setColumns(20);
        txtAddressN.setRows(5);
        jScrollPane2.setViewportView(txtAddressN);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 70));

        jLabel16.setText("Gender");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        buttonGroup2.add(radioMaleN);
        radioMaleN.setText("Male");
        jPanel5.add(radioMaleN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        buttonGroup2.add(radioFemaleN);
        radioFemaleN.setText("Female");
        jPanel5.add(radioFemaleN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));
        jPanel5.add(txtNICN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));

        jLabel17.setText("NIC No.");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, 20));

        btnNewNurse.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnNewNurse.setForeground(new java.awt.Color(0, 0, 255));
        btnNewNurse.setText("Add New Nurse");
        jPanel5.add(btnNewNurse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 269, -1, 40));
        jPanel5.add(txtTelN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));
        jPanel5.add(txtMailN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 30));
        jPanel5.add(txtWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 130, 30));

        jLabel19.setText("Ward No.");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, -1, 30));

        jLabel20.setText("e-mail");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));

        jLabel21.setText("Tel. No.");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel31.setText("Employee ID");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 40));

        txtEmpIDN.setEditable(false);
        txtEmpIDN.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpIDN.setForeground(new java.awt.Color(0, 0, 255));
        jPanel5.add(txtEmpIDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, 40));

        btnGenerateN.setForeground(new java.awt.Color(255, 0, 0));
        btnGenerateN.setText("Generate");
        jPanel5.add(btnGenerateN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jTabbedPane3.addTab("Nurse", jPanel5);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Staff ID");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        txtStaffID.setEditable(false);
        txtStaffID.setBackground(new java.awt.Color(204, 204, 204));
        txtStaffID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel3.add(txtStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 40));

        jLabel23.setText("First Name");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));
        jPanel3.add(txtFNameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));
        jPanel3.add(txtLNameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel24.setText("Last Name");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel25.setText("Address");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        txtAddressS.setColumns(20);
        txtAddressS.setRows(5);
        jScrollPane3.setViewportView(txtAddressS);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 70));

        jLabel26.setText("Gender");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        buttonGroup3.add(radioMaleS);
        radioMaleS.setText("Male");
        jPanel3.add(radioMaleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        buttonGroup3.add(radioFemaleS);
        radioFemaleS.setText("Female");
        jPanel3.add(radioFemaleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel27.setText("NIC No.");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, 20));
        jPanel3.add(txtNICS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));
        jPanel3.add(txtTelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));

        jLabel28.setText("Tel. No.");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel30.setText("Profession");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, -1, 30));
        jPanel3.add(txtProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 130, 30));

        jLabel32.setText("Employee ID");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 40));

        txtEmpIDS.setEditable(false);
        txtEmpIDS.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpIDS.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.add(txtEmpIDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, 40));

        btnNewStaff.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnNewStaff.setForeground(new java.awt.Color(0, 0, 255));
        btnNewStaff.setText("Add New Staff Member");
        jPanel3.add(btnNewStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 269, -1, 40));

        btnGenerateS.setForeground(new java.awt.Color(255, 0, 0));
        btnGenerateS.setText("Generate");
        jPanel3.add(btnGenerateS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel33.setText("e-mail");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));
        jPanel3.add(txtMailS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 220, 30));

        jTabbedPane3.addTab("Maintenance Staff", jPanel3);

        jPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 370));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        btnClear.setText("Clear");
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIFactory.showUI(UIFactory.UIName.ADDNEWEMPLOYEE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnGenerateN;
    private javax.swing.JButton btnGenerateS;
    private javax.swing.JButton btnNewDoc;
    private javax.swing.JButton btnNewNurse;
    private javax.swing.JButton btnNewStaff;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JRadioButton radioFemale;
    public javax.swing.JRadioButton radioFemaleN;
    public javax.swing.JRadioButton radioFemaleS;
    public javax.swing.JRadioButton radioMale;
    public javax.swing.JRadioButton radioMaleN;
    public javax.swing.JRadioButton radioMaleS;
    public javax.swing.JTextArea txtAddress;
    public javax.swing.JTextArea txtAddressN;
    public javax.swing.JTextArea txtAddressS;
    public javax.swing.JTextField txtDocID;
    public javax.swing.JTextField txtEmpID;
    public javax.swing.JTextField txtEmpIDN;
    public javax.swing.JTextField txtEmpIDS;
    public javax.swing.JTextField txtFName;
    public javax.swing.JTextField txtFNameN;
    public javax.swing.JTextField txtFNameS;
    public javax.swing.JTextField txtLName;
    public javax.swing.JTextField txtLNameN;
    public javax.swing.JTextField txtLNameS;
    public javax.swing.JTextField txtMail;
    public javax.swing.JTextField txtMailN;
    public javax.swing.JTextField txtMailS;
    public javax.swing.JTextField txtNIC;
    public javax.swing.JTextField txtNICN;
    public javax.swing.JTextField txtNICS;
    public javax.swing.JTextField txtNurseID;
    public javax.swing.JTextField txtProfession;
    public javax.swing.JTextField txtSLMC;
    public javax.swing.JTextField txtStaffID;
    public javax.swing.JTextField txtTel;
    public javax.swing.JTextField txtTelN;
    public javax.swing.JTextField txtTelS;
    public javax.swing.JTextField txtWardNo;
    // End of variables declaration//GEN-END:variables

    
    //returning every button
    public JButton getBtnBack(){
        return btnBack;
    }

    public JButton getBtnGenerate() {
        return btnGenerate;
    }
    
    public JButton getBtnNewDoc(){
        return btnNewDoc;
    }
    
    public JButton getBtnGenerateN(){
        return btnGenerateN;
    }
    
    public JButton getBtnNewNurse(){
        return btnNewNurse;
    }
    
    public JButton getBtnGenerateS(){
        return btnGenerateS;
    }
    
    public JButton getBtnNewStaff(){
        return btnNewStaff;
    }
    
    public JButton getBtnClear(){
        return btnClear;
    }
}
