/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.*/
//import Login;
package EmployeeDetails;

import javax.swing.JButton;
import util.UIFactory;
import util.View;


/**
 *
 * @author SiziJayawardena
 */
public class EmployeeDetails extends javax.swing.JFrame implements View{

    /**
     * Creates new form Employee
     */
    public EmployeeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDocID = new javax.swing.JTextField();
        btnSearchD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLNameD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFNameD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMailD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSLMCD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddressD = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtEmpIDD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioFemaleD = new javax.swing.JRadioButton();
        radioMaleD = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtTelD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNICD = new javax.swing.JTextField();
        btnUpdateD = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnSearchN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtFNameN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLNameN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddressN = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtEmpIDN = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTelN = new javax.swing.JTextField();
        txtNICN = new javax.swing.JTextField();
        radioMaleN = new javax.swing.JRadioButton();
        radioFemaleN = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtWardNo = new javax.swing.JTextField();
        btnUpdateN = new javax.swing.JButton();
        txtNurseID = new javax.swing.JTextField();
        txtMailN = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btnSearchS = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtFNameS = new javax.swing.JTextField();
        txtLNameS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressS = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        radioMaleS = new javax.swing.JRadioButton();
        radioFemaleS = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        txtNICS = new javax.swing.JTextField();
        txtTelS = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtEmpIDS = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        btnUpdateS = new javax.swing.JButton();
        txtStaffID = new javax.swing.JTextField();
        txtMailS = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        txtAttenEmpID = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtAttenID = new javax.swing.JTextField();
        btnAttenAdd = new javax.swing.JButton();
        btnAttenGenerate = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtAttenFName = new javax.swing.JTextField();
        txtAttenLName = new javax.swing.JTextField();
        txtAttenDays = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtAttenMonth = new javax.swing.JTextField();
        btnAttenSearch = new javax.swing.JButton();
        btnAttenUpdate = new javax.swing.JButton();
        lblDNS = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txtAttenEmpIDV = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtAttenMonthV = new javax.swing.JTextField();
        btnAttenSearchV = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        txtAttenFNameV = new javax.swing.JTextField();
        txtAttenLNameV = new javax.swing.JTextField();
        txtAttenIDV = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtAttenDaysV = new javax.swing.JTextField();
        lblDNSV = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtSalaryEmpID = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnSalarySearch = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        txtSalaryMonth = new javax.swing.JTextField();
        txtSalaryFName = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtSalaryLName = new javax.swing.JTextField();
        txtSalaryTotal = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtSalaryID = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setForeground(new java.awt.Color(51, 51, 255));
        jTabbedPane3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Doctor ID");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        txtDocID.setBackground(new java.awt.Color(204, 255, 255));
        txtDocID.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtDocID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel4.add(txtDocID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 40));

        btnSearchD.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchD.setForeground(new java.awt.Color(0, 51, 255));
        btnSearchD.setText("Search");
        jPanel4.add(btnSearchD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel2.setText("First Name");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));
        jPanel4.add(txtLNameD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel3.setText("Employee ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));
        jPanel4.add(txtFNameD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));

        jLabel4.setText("SLMC Registered No.");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, -1, 30));
        jPanel4.add(txtMailD, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 30));

        jLabel5.setText("Address");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));
        jPanel4.add(txtSLMCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 130, 30));

        jLabel6.setText("Last Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        txtAddressD.setColumns(20);
        txtAddressD.setRows(5);
        jScrollPane1.setViewportView(txtAddressD);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 70));

        jLabel7.setText("Tel. No.");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        txtEmpIDD.setEditable(false);
        txtEmpIDD.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.add(txtEmpIDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 30));

        jLabel8.setText("Gender");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        buttonGroup1.add(radioFemaleD);
        radioFemaleD.setText("Female");
        jPanel4.add(radioFemaleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        buttonGroup1.add(radioMaleD);
        radioMaleD.setText("Male");
        jPanel4.add(radioMaleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel9.setText("e-mail");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 30));

        txtTelD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelDActionPerformed(evt);
            }
        });
        jPanel4.add(txtTelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));

        jLabel10.setText("NIC No.");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, 20));
        jPanel4.add(txtNICD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));

        btnUpdateD.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdateD.setForeground(new java.awt.Color(51, 51, 255));
        btnUpdateD.setText("Update");
        jPanel4.add(btnUpdateD, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 19, 100, 40));

        jTabbedPane3.addTab("Doctor", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Nurse ID");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        btnSearchN.setForeground(new java.awt.Color(51, 51, 255));
        btnSearchN.setText("Search");
        jPanel5.add(btnSearchN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel12.setText("First Name");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));
        jPanel5.add(txtFNameN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));

        jLabel13.setText("Last Name");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));
        jPanel5.add(txtLNameN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        txtAddressN.setColumns(20);
        txtAddressN.setRows(5);
        jScrollPane2.setViewportView(txtAddressN);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 70));

        jLabel14.setText("Address");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        txtEmpIDN.setEditable(false);
        txtEmpIDN.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.add(txtEmpIDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 30));

        jLabel16.setText("Employee ID");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));

        jLabel17.setText("Tel. No.");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));
        jPanel5.add(txtTelN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));
        jPanel5.add(txtNICN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));

        buttonGroup2.add(radioMaleN);
        radioMaleN.setText("Male");
        jPanel5.add(radioMaleN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        buttonGroup2.add(radioFemaleN);
        radioFemaleN.setText("Female");
        jPanel5.add(radioFemaleN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel19.setText("Gender");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        jLabel20.setText("NIC No.");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, 20));

        jLabel18.setText("Employee ID");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));
        jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));

        jLabel15.setText("First Name");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));

        jLabel21.setText("Ward No.");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, -1, 30));
        jPanel5.add(txtWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 130, 30));

        btnUpdateN.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnUpdateN.setForeground(new java.awt.Color(51, 51, 255));
        btnUpdateN.setText("Update");
        jPanel5.add(btnUpdateN, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 19, 100, 40));

        txtNurseID.setBackground(new java.awt.Color(204, 255, 255));
        txtNurseID.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtNurseID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel5.add(txtNurseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 40));
        jPanel5.add(txtMailN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 30));

        jLabel37.setText("e-mail");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 30));

        jTabbedPane3.addTab("Nurse", jPanel5);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Staff ID");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        btnSearchS.setForeground(new java.awt.Color(0, 0, 255));
        btnSearchS.setText("Search");
        jPanel3.add(btnSearchS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel23.setText("First Name");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, 30));
        jPanel3.add(txtFNameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 140, 30));
        jPanel3.add(txtLNameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel24.setText("Last Name");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel25.setText("Address");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        txtAddressS.setColumns(20);
        txtAddressS.setRows(5);
        jScrollPane3.setViewportView(txtAddressS);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 70));

        jLabel26.setText("Gender");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 20));

        buttonGroup3.add(radioMaleS);
        radioMaleS.setText("Male");
        jPanel3.add(radioMaleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        buttonGroup3.add(radioFemaleS);
        radioFemaleS.setText("Female");
        jPanel3.add(radioFemaleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel27.setText("NIC No.");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, 20));
        jPanel3.add(txtNICS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));
        jPanel3.add(txtTelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));

        jLabel28.setText("Tel. No.");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel29.setText("Employee ID");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));

        txtEmpIDS.setEditable(false);
        txtEmpIDS.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.add(txtEmpIDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 30));

        jLabel30.setText("Profession");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 86, -1, 30));
        jPanel3.add(txtProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 86, 130, 30));

        btnUpdateS.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnUpdateS.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdateS.setText("Update");
        jPanel3.add(btnUpdateS, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 19, 100, 40));

        txtStaffID.setBackground(new java.awt.Color(204, 255, 255));
        txtStaffID.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtStaffID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel3.add(txtStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 40));
        jPanel3.add(txtMailS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 30));

        jLabel38.setText("e-mail");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 30));

        jTabbedPane3.addTab("Maintenance Staff", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAttenEmpID.setBackground(new java.awt.Color(204, 255, 255));
        txtAttenEmpID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel7.add(txtAttenEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 30));

        jLabel31.setText("Employee ID");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel39.setText("Attendance ID");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        txtAttenID.setEditable(false);
        txtAttenID.setBackground(new java.awt.Color(204, 255, 255));
        txtAttenID.setForeground(new java.awt.Color(255, 51, 51));
        jPanel7.add(txtAttenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 90, 30));

        btnAttenAdd.setForeground(new java.awt.Color(51, 51, 255));
        btnAttenAdd.setText("Add");
        jPanel7.add(btnAttenAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 30));

        btnAttenGenerate.setForeground(new java.awt.Color(255, 51, 51));
        btnAttenGenerate.setText("Generate");
        btnAttenGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttenGenerateActionPerformed(evt);
            }
        });
        jPanel7.add(btnAttenGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, 30));

        jLabel32.setText("Name");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));
        jPanel7.add(txtAttenFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));
        jPanel7.add(txtAttenLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 130, 30));

        txtAttenDays.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAttenDays.setForeground(new java.awt.Color(51, 51, 255));
        jPanel7.add(txtAttenDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 120, 30));

        jLabel33.setText("Number of Days");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 30));

        jLabel40.setText("Month");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 30));

        txtAttenMonth.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAttenMonth.setForeground(new java.awt.Color(51, 51, 255));
        jPanel7.add(txtAttenMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 120, 30));

        btnAttenSearch.setForeground(new java.awt.Color(51, 51, 255));
        btnAttenSearch.setText("Search");
        btnAttenSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttenSearchActionPerformed(evt);
            }
        });
        jPanel7.add(btnAttenSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 30));

        btnAttenUpdate.setForeground(new java.awt.Color(51, 51, 255));
        btnAttenUpdate.setText("Update");
        jPanel7.add(btnAttenUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, 30));

        lblDNS.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 18)); // NOI18N
        lblDNS.setForeground(new java.awt.Color(51, 51, 255));
        lblDNS.setText("******");
        jPanel7.add(lblDNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jTabbedPane1.addTab("Add New Attendance", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setText("Employee ID");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        txtAttenEmpIDV.setBackground(new java.awt.Color(204, 255, 255));
        txtAttenEmpIDV.setForeground(new java.awt.Color(51, 51, 255));
        jPanel8.add(txtAttenEmpIDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 30));

        jLabel42.setText("Month");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        txtAttenMonthV.setBackground(new java.awt.Color(204, 255, 255));
        txtAttenMonthV.setForeground(new java.awt.Color(51, 51, 255));
        jPanel8.add(txtAttenMonthV, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 30));

        btnAttenSearchV.setForeground(new java.awt.Color(51, 51, 255));
        btnAttenSearchV.setText("Search");
        btnAttenSearchV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttenSearchVActionPerformed(evt);
            }
        });
        jPanel8.add(btnAttenSearchV, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 30));

        jLabel43.setText("Name");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        txtAttenFNameV.setEditable(false);
        jPanel8.add(txtAttenFNameV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        txtAttenLNameV.setEditable(false);
        jPanel8.add(txtAttenLNameV, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 130, 30));

        txtAttenIDV.setEditable(false);
        txtAttenIDV.setBackground(new java.awt.Color(102, 255, 255));
        txtAttenIDV.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAttenIDV.setForeground(new java.awt.Color(51, 51, 255));
        jPanel8.add(txtAttenIDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 90, 30));

        jLabel44.setText("Attendance ID");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 30));

        jLabel45.setText("Number of Days");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 30));

        txtAttenDaysV.setEditable(false);
        txtAttenDaysV.setBackground(new java.awt.Color(204, 255, 204));
        txtAttenDaysV.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAttenDaysV.setForeground(new java.awt.Color(51, 51, 255));
        jPanel8.add(txtAttenDaysV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 90, 30));

        lblDNSV.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 18)); // NOI18N
        lblDNSV.setForeground(new java.awt.Color(51, 51, 255));
        lblDNSV.setText("******");
        jPanel8.add(lblDNSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jTabbedPane1.addTab("View Records", jPanel8);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 320));

        jTabbedPane3.addTab("Attendance", jPanel2);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSalaryEmpID.setBackground(new java.awt.Color(204, 255, 255));
        txtSalaryEmpID.setForeground(new java.awt.Color(51, 51, 255));
        jPanel6.add(txtSalaryEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, 30));

        jLabel34.setText("Employee ID");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 30));

        btnSalarySearch.setForeground(new java.awt.Color(51, 51, 255));
        btnSalarySearch.setText("Search");
        jPanel6.add(btnSalarySearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 30));

        jLabel47.setText("Month");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 30));

        txtSalaryMonth.setBackground(new java.awt.Color(204, 255, 255));
        txtSalaryMonth.setForeground(new java.awt.Color(51, 51, 255));
        jPanel6.add(txtSalaryMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, 30));

        txtSalaryFName.setEditable(false);
        jPanel6.add(txtSalaryFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, 30));

        jLabel46.setText("Name");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 30));

        txtSalaryLName.setEditable(false);
        jPanel6.add(txtSalaryLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 160, 30));

        txtSalaryTotal.setEditable(false);
        txtSalaryTotal.setBackground(new java.awt.Color(255, 204, 204));
        txtSalaryTotal.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSalaryTotal.setForeground(new java.awt.Color(51, 51, 255));
        jPanel6.add(txtSalaryTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 120, 30));

        jLabel36.setText("Total Salary Amount");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 130, 30));

        jLabel48.setText("PaySheet No.");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 30));

        txtSalaryID.setEditable(false);
        txtSalaryID.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.add(txtSalaryID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 30));

        jTabbedPane3.addTab("Salary", jPanel6);

        jPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 370));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtTelDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelDActionPerformed

    private void btnAttenGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttenGenerateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttenGenerateActionPerformed

    private void btnAttenSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttenSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttenSearchActionPerformed

    private void btnAttenSearchVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttenSearchVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttenSearchVActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIFactory.showUI(UIFactory.UIName.EMPLOYEEDETAILS);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttenAdd;
    private javax.swing.JButton btnAttenGenerate;
    private javax.swing.JButton btnAttenSearch;
    private javax.swing.JButton btnAttenSearchV;
    private javax.swing.JButton btnAttenUpdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSalarySearch;
    private javax.swing.JButton btnSearchD;
    private javax.swing.JButton btnSearchN;
    private javax.swing.JButton btnSearchS;
    private javax.swing.JButton btnUpdateD;
    private javax.swing.JButton btnUpdateN;
    private javax.swing.JButton btnUpdateS;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField12;
    public javax.swing.JLabel lblDNS;
    public javax.swing.JLabel lblDNSV;
    public javax.swing.JRadioButton radioFemaleD;
    public javax.swing.JRadioButton radioFemaleN;
    public javax.swing.JRadioButton radioFemaleS;
    public javax.swing.JRadioButton radioMaleD;
    public javax.swing.JRadioButton radioMaleN;
    public javax.swing.JRadioButton radioMaleS;
    public javax.swing.JTextArea txtAddressD;
    public javax.swing.JTextArea txtAddressN;
    public javax.swing.JTextArea txtAddressS;
    public javax.swing.JTextField txtAttenDays;
    public javax.swing.JTextField txtAttenDaysV;
    public javax.swing.JTextField txtAttenEmpID;
    public javax.swing.JTextField txtAttenEmpIDV;
    public javax.swing.JTextField txtAttenFName;
    public javax.swing.JTextField txtAttenFNameV;
    public javax.swing.JTextField txtAttenID;
    public javax.swing.JTextField txtAttenIDV;
    public javax.swing.JTextField txtAttenLName;
    public javax.swing.JTextField txtAttenLNameV;
    public javax.swing.JTextField txtAttenMonth;
    public javax.swing.JTextField txtAttenMonthV;
    public javax.swing.JTextField txtDocID;
    public javax.swing.JTextField txtEmpIDD;
    public javax.swing.JTextField txtEmpIDN;
    public javax.swing.JTextField txtEmpIDS;
    public javax.swing.JTextField txtFNameD;
    public javax.swing.JTextField txtFNameN;
    public javax.swing.JTextField txtFNameS;
    public javax.swing.JTextField txtLNameD;
    public javax.swing.JTextField txtLNameN;
    public javax.swing.JTextField txtLNameS;
    public javax.swing.JTextField txtMailD;
    public javax.swing.JTextField txtMailN;
    public javax.swing.JTextField txtMailS;
    public javax.swing.JTextField txtNICD;
    public javax.swing.JTextField txtNICN;
    public javax.swing.JTextField txtNICS;
    public javax.swing.JTextField txtNurseID;
    public javax.swing.JTextField txtProfession;
    public javax.swing.JTextField txtSLMCD;
    public javax.swing.JTextField txtSalaryEmpID;
    public javax.swing.JTextField txtSalaryFName;
    public javax.swing.JTextField txtSalaryID;
    public javax.swing.JTextField txtSalaryLName;
    public javax.swing.JTextField txtSalaryMonth;
    public javax.swing.JTextField txtSalaryTotal;
    public javax.swing.JTextField txtStaffID;
    public javax.swing.JTextField txtTelD;
    public javax.swing.JTextField txtTelN;
    public javax.swing.JTextField txtTelS;
    public javax.swing.JTextField txtWardNo;
    // End of variables declaration//GEN-END:variables

    
    //return every button
    public JButton getBtnBack() {
        return btnBack;
    }
    
    public JButton getBtnSearchD(){
        return btnSearchD;
    }
    
    public JButton getBtnSearchN(){
        return btnSearchN;
    }
    
    public JButton getBtnSearchS(){
        return btnSearchS;
    }
    
    public JButton getBtnUpdateD(){
        return btnUpdateD;
    }
    
    public JButton getBtnUpdateN(){
        return btnUpdateN;
    }
    
    public JButton getBtnUpdateS(){
        return btnUpdateS;
    }
    
    public JButton getBtnAttenSearch(){
        return btnAttenSearch;
    }
    
    public JButton getBtnAttenAdd(){
        return btnAttenAdd;
    }
    
    public JButton getBtnAttenGenerate(){
        return btnAttenGenerate;
    }
    
    public JButton getBtnAttenSearchV(){
        return btnAttenSearchV;
    }
    
    public JButton getBtnSalarySearch(){
        return btnSalarySearch;
    }

    public JButton getBtnAttenUpdate() {
        return btnAttenUpdate;
    }
    
    public JButton getBtnClear(){
        return btnClear;
    }
    
    
}
